config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post 'sessions' => 'sessions#create'
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  devise_for :users

  root 'users#index'
  get '/users', to: 'users#index', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  
  get '/users/:user_id/posts/', to: 'posts#index', as: 'user_posts'
  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts/', to: 'posts#create', as: 'create_post'
  delete '/users/:user_id/posts/:id', to: 'posts#destroy', as: 'delete_post'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'

  get '/users/:user_id/posts/:id/comments/new', to: 'comments#new', as: 'new_comment'
  post '/users/:user_id/posts/:id/comments', to: 'comments#create', as: 'create_comment'
  delete '/users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy', as: 'delete_comment'

  get '/likes/:id/create', to: 'likes#create', as: 'increment_likes'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  attribute :posts_counter, :integer, default: 0
  attribute :photo, :string, default: 'http://cdn.onlinewebfonts.com/svg/img_264570.png'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_save :generate_api_token

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def generate_api_token
    self.api_token = SecureRandom.hex(16)
    puts "Generate API Token: #{api_token}"
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.all
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_details_for(user)
    content_tag(:div, class: 'user-details') do
      concat(content_tag(:h2, link_to(user.name, user_path(user), class: 'custom-link')))
      concat(content_tag(:p, "Number of posts: #{user.posts_counter}", class: 'user-posts-counter'))
    end
  end
end

app/views/users/_users_display.erb
<div class="Users-list">
  <% @users.each do |user| %>
    <div class="User-item">
      <img src="<%= user.photo %>" alt="userPhoto" >
      <%= user_details_for(user) %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<html>

  <body>
    <%= render 'users_display' %>
  </body>
  
</html>

app/views/users/show.html.erb
<html>

<body>
  <div class="User-profile">
    <% if @user %>
      <%= render 'shared/user_card', user: @user %>

    <div class="User-bio">
      <h2>Bio</h2>
      <% if @user.bio.present? %>
        <p><%= h(@user.bio) %></p>
      <% else %>
        <p>Bio not found</p>
      <% end %>
    </div>

      <% else %>
      <p>User not found.</p>
    <% end %>

    <hr>

    <%= render partial: 'shared/posts_card', locals: { posts: @user.posts } %>

    <div class="User-actions">
      <%= button_to "Go Back", users_path, method: :get, class: "Go-back-button" %>
      <%= button_to "View All Posts", user_posts_path(user_id: @user.id), method: :get, class: "Submit-button" %>
    </div>
  </div>
</body>
</html>