config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post 'sessions' => 'sessions#create'
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  devise_for :users

  root 'users#index'
  get '/users', to: 'users#index', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  
  get '/users/:user_id/posts/', to: 'posts#index', as: 'user_posts'
  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts/', to: 'posts#create', as: 'create_post'
  delete '/users/:user_id/posts/:id', to: 'posts#destroy', as: 'delete_post'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'

  get '/users/:user_id/posts/:id/comments/new', to: 'comments#new', as: 'new_comment'
  post '/users/:user_id/posts/:id/comments', to: 'comments#create', as: 'create_comment'
  delete '/users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy', as: 'delete_comment'

  get '/likes/:id/create', to: 'likes#create', as: 'increment_likes'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_many :likes
  has_many :comments

  attribute :comments_counter, :integer, default: 0
  attribute :likes_counter, :integer, default: 0

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :increment_post_count
  after_destroy :decrement_post_count

  def increment_post_count
    puts 'Increment Post Count'
    user.increment!(:posts_counter)
  end

  def decrement_post_count
    puts 'Decrement Post Count'
    user.decrement!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    posts = User.find(params['user_id']).posts
    render json: posts
  rescue StandardError
    render json: { error: 'User not found' }, status: :bad_request
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:user, comments: :user)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @user = User.find(params[:user_id])
  end

  def create
    @post = User.find(params[:user_id]).posts.build(post_params)
    return unless @post.save

    redirect_to user_posts_path, notice: 'Post Created'
  end

  def destroy
    @post = Post.find(params[:id])
    return unless @post.destroy

    redirect_to user_posts_path, notice: 'Post Deleted'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_text_section(post)
    content_tag(:div, class: 'text') do
      concat content_tag(:p, "Comments: #{post.comments_counter.nil? ? 0 : post.comments_counter}",
                         class: 'comment-text')
      concat link_to 'Likes: ', increment_likes_path(post), method: :post, remote: true, class: 'like-counter',
                                                            id: "like-link-#{post.id}"
      concat content_tag(:span, post.likes_counter.nil? ? 0 : post.likes_counter, class: 'like-counter-number',
                                                                                  id: "like-counter-#{post.id}")
    end
  end

  def render_comments_section(post)
    content_tag(:div, class: 'comments-section') do
      content_tag(:h4, 'Comments:', class: 'section-comments') +
        if post.comments.blank?
          content_tag(:p, 'no comments for the moment', class: 'ul-comments-box')
        else
          content_tag(:ul, class: 'ul-comments-box') do
            post.comments.each do |comment|
              user_name = comment.user ? comment.user.name : 'Anonymous'
              comment_text = "#{user_name}: #{comment.text}"
              delete_link = if current_user == post.user || can?(:delete, comment)
                              button_to('Delete', delete_comment_path(comment.user, post, comment),
                                        method: :delete,
                                        data: { turbo_method: :delete, turbo_confirm: 'Delete Comment?' },
                                        class: 'Delete-button')
                            end

              concat content_tag(:li, "#{comment_text} #{delete_link}".html_safe, class: 'comment-li')
            end
          end
        end
    end
  end
end

app/views/posts/_post_card.erb
<div class="Post-section">
  <div class="Post-details">
    <%= render_text_section(@post) %>
    <div class="Post-info">
      <p>Title: <%= @post.title %></p>
      <p>by: <%= @post.user.name %></p>
    </div>
    <p class="Post-text">Text: <%= @post.text %></p>
  </div>
</div>

app/views/posts/_posts_display.erb
<div class="Posts-section">
  <% if @posts.any? %>
    <% @posts.each do |post| %>
      <div class="Post-item">
        <div class="Post-actions">
          <h3><%= link_to post.title, user_post_path(user_id: post.author_id, id: post.id), class: "Post-title" %></h3>
          <% if current_user == post.user || can?(:delete, post) %>
            <%= link_to 'Delete', delete_post_path(user_id: post.author_id, id: post.id), data: { turbo_method: :delete, turbo_confirm: 'Delete Post?' }, class: "Delete-button" %>
          <% end %>
        </div>
        <p><%= post.text %></p>
        <p>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
        <%= render_comments_section(post) %>
      </div>
    <% end %>
  <% else %>
    <p>No posts found.</p>
  <% end %>
</div>

app/views/posts/index.html.erb
<html>

<body>
  <div class="Post-container">
    <%= render 'shared/user_card', user: @user %>

    <%= render 'posts_display' %>

    <div class="User-actions">
      <%= button_to "Go Back", user_path(@user), method: :get, class: "Go-back-button" %>
      <%= button_to 'New Post', new_user_post_path, method: :get, class: "Submit-button" %>
    </div>
  </div>
</body>

</html>

app/views/posts/new.html.erb
<div class="New-post-form">
  <h1>New Post</h1>
  <%= form_with(model: @post, url: user_posts_path(current_user)) do |form| %>
    <div class="Form-field">
      <%= form.label :title %>
      <%= form.text_field :title, class: "Form-input" %>
    </div>

    <div class="Form-field">
      <%= form.label :content %>
      <%= form.text_area :text, rows: 6, class: "Form-textarea" %>
    </div>

    <%= form.submit "Create Post", class: "Submit-button" %>
  <% end %>
</div>

<%= button_to "Go Back", user_posts_path(current_user), method: :get, class: "Go-back-button" %>

app/views/posts/show.html.erb
<html>

<body>
  <div class="Page-container">
    <%= render 'post_card' %>

    <%= render_comments_section(@post) %>

    <div class="User-actions">
      <%= button_to "Go Back", user_posts_path(current_user), method: :get, class: "Go-back-button" %>
      <%= button_to 'New Comment', new_comment_path, method: :get, class: "Submit-button" %>
    </div>
  </div>
</body>

</html>